name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Очистка целевой директории на сервере
      - name: Clean target directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/test-front-1.com/html/*

      # 3. Копирование файлов проекта на сервер
      - name: Copy project files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/var/www/test-front-1.com/html"

      # 4. Настройка Nginx для работы с контейнером
      - name: Update Nginx configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Обновите конфигурацию Nginx
            sudo tee /etc/nginx/sites-available/test-front-1 <<EOF
            server {
              listen 80;
              server_name victor-test-list.ageneroj.beget.tech;
      
              location / {
                proxy_pass http://localhost:81;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
                
                try_files \$uri /index.html;
              }
            }
            EOF

            # Проверьте конфигурацию Nginx
            sudo nginx -t
            
            sudo ln -s /etc/nginx/sites-available/test-front-1 /etc/nginx/sites-enabled/

            # Перезапустите Nginx
            sudo systemctl restart nginx

      # 5. Запуск Docker-контейнера
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test-front-1.com/html
            
            # Соберите Docker-образ
            docker build -t test-task-frontend-image .

            # Остановите и удалите старый контейнер
            docker stop test-task-frontend-container || true
            docker rm test-task-frontend-container || true

            # Запустите новый контейнер
            docker run -d \
              --name test-task-frontend-container \
              -p 81:80 \
              test-task-frontend-image
